name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/momentum/**'
      - '.github/workflows/docs.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo myst-parser sphinx-autodoc-typehints sphinx-markdown-builder sphinx-copybutton sphinxcontrib-autoprogram
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
